/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LtSocket;

import java.net.InetAddress;

/**
 *
 * @author Ngo Tien Phong
 */
public class LtSocket extends javax.swing.JFrame {

    /**
     * Creates new form LtSocket
     */
    public LtSocket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTenMay = new javax.swing.JTextField();
        txtIp = new javax.swing.JTextField();
        list1 = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTenMay.setText("jTextField1");
        txtTenMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenMayActionPerformed(evt);
            }
        });
        getContentPane().add(txtTenMay, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 59, 100, -1));

        txtIp.setText("jTextField1");
        getContentPane().add(txtIp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, -1));
        getContentPane().add(list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 260, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenMayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenMayActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            InetAddress description =  InetAddress.getLocalHost();
            
             txtTenMay.setText(description.getHostName());
             txtIp.setText(description.getHostAddress());
            
            // netstat - a ipconfig  ping
            InetAddress[] ds = InetAddress.getAllByName("sangtacviet.com");
//            for (InetAddress gt :ds) {
//                list1.add(gt.getHostAddress());
//            }


            for (int i = 1; i < 256; i++) {
                String ip = "10.10.64." + String.valueOf(i);
                InetAddress tam = InetAddress.getByName(ip);
                list1.add(tam.getHostName());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LtSocket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LtSocket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LtSocket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LtSocket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LtSocket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List list1;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtTenMay;
    // End of variables declaration//GEN-END:variables
}
