/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package threadexcercise;

/**
 *
 * @author Jack Phong
 */
public class Ex2Form extends javax.swing.JFrame {

    /**
     *
     * @param n int
     * @param k int
     * @return 
     */
    public int combination(int n, int k) {
        if (k > n) {
            return 0; // Nếu k lớn hơn n, không có tổ hợp nào tồn tại
        }

        int result = 1;
        for (int i = 1; i <= k; i++) {
            result = result * (n - i + 1) / i;
        }

        return result;
    }

    
    int s, s1 = 0, s2 = 0, s3 = 0, s4 = 0;
    boolean kt1 = false, kt2 = false, kt3 = false, kt4 = false;
    public class Tuyen extends Thread {
        int td;
        int n;
        int k;
        public Tuyen(int td, int n, int k) {
            this.td = td;
            this.n = n;
            this.k = k;
        }
        
        public void run() {
            if (td == 1) {
                s1 = combination(n - 2, k);
                kt1 = true;
            }
            if (td == 2) {
                s2 = combination(n - 2, k - 1);
                kt2 = true;
            }
            if (td == 3) {
                s3 = combination(n - 2, k - 1);
                kt3 = true;
            }
            if (td == 4) {
                s4 = combination(n - 2, k - 2);
                kt4 = true;
            }
            
            if (td == 5) {
                while (true) {
                    if (kt1 && kt2 && kt3 && kt4 ) {
                        System.out.println("\nT1 :: "+  s1 + "\nT2 :: " + s2 + "\nT3 :: " + s3 + "\nT4 :: " + s4);
                        s = s1 + s2 + s3 + s4;
                        resultTxt.setText(String.valueOf(s));
                        break;
                    }
                }
            }
        }
    }
    /**
     * Creates new form Ex2Form
     */
    public Ex2Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        nTxt = new javax.swing.JTextField();
        kTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resultTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Tính");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        nTxt.setText("n");
        nTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 260, -1));

        kTxt.setText("k");
        kTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kTxtMouseClicked(evt);
            }
        });
        kTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kTxtActionPerformed(evt);
            }
        });
        getContentPane().add(kTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 260, -1));

        jLabel1.setText("Nhập k");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, -1));

        jLabel2.setText("Kết quả");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 70, -1));
        getContentPane().add(resultTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, -1));

        jLabel3.setText("Nhập n");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n = Integer.parseInt(nTxt.getText());
        int k = Integer.parseInt(kTxt.getText());
        
        for (int i = 1; i <= 5; i++) {
            Tuyen t = new Tuyen(i, n, k);
            t.start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nTxtActionPerformed
        // TODO add your handling code here:
        nTxt.setText("");
    }//GEN-LAST:event_nTxtActionPerformed

    private void kTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kTxtMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_kTxtMouseClicked

    private void kTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kTxtActionPerformed
        // TODO add your handling code here:
        kTxt.setText("");
    }//GEN-LAST:event_kTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex2Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField kTxt;
    private javax.swing.JTextField nTxt;
    private javax.swing.JTextField resultTxt;
    // End of variables declaration//GEN-END:variables
}
